### ISSUE TITLE
Hi Sahil, are you going to update now Angular is at version 2 stable?

### ISSUE THREAD

**Issue by nigel-dewar** [maliksahil/Angular2ADAL#1]
Hi Sahil, are you going to update now Angular is at version 2 stable?.

I love this library of yours, I think its the best out.

Cheers

**Comment by maliksahil** [comment]
I've submitted this to angular.io. Waiting on them to publish it.

**Comment by nigel-dewar** [comment]
Ok great. Thank you Sahil.

Sent from Samsung Mobile

-------- Original message --------
From: Sahil Malik
Date:16/11/2016 15:36 (GMT+10:00)
To: maliksahil/Angular2AzureADAuthLib
Cc: nigel-dewar , Author
Subject: Re: [maliksahil/Angular2AzureADAuthLib] Hi Sahil, are you going to update now Angular is at version 2 stable? (#1)

I've submitted this to angular.io. Waiting on them to publish it.

##

**Comment by nigel-dewar** [comment]
Just FYI, also, Ive tried several samples, even one from Microsoft graph team, and they can sign in, but fail when trying to access O365 resources, like files, messages etc. Your example works 100% with no issues. I used the same azure ad permissions on the microsoft app, as with your sample app. microsofts one fails, and yours works.

Keep up the great work, hopefully your submission gets published soon. And microsoft takes note of it also.

Cheers

Nigel

**Comment by nigel-dewar** [comment]
There is only one confusion however for me, running this sample works but I do see this error in the console. 

![image](https://cloud.githubusercontent.com/assets/9402456/20337984/0ffde10c-ac20-11e6-94c3-70704715990d.png)
