### ISSUE TITLE
Accessing AzureAD protected APIs

### ISSUE THREAD

**Issue by nikhil263** [maliksahil/Angular2ADAL#2]
Quick question, is there any way where can access external Azure AD protected end-points ?  

In service constants looks like we can only pass Graph API.

`var azureADAuthHelper = new AzureADAuthHelper(new ServiceConstants("b8ba835b-a082-4e17-a9d3-ce58a349fe15", "conmet.onmicrosoft.com", "http://localhost:3000/"));`

I was wondering whether we can call external API like ADAL.js

` var endpoints = {

        // Map the location of a request to an API to a the identifier of the associated resource
        "https://localhost:44375/": "https://abc.onmicrosoft.com/abc",
    };

    adalProvider.init(
        {
            instance: 'https://login.microsoftonline.com/',
            tenant: 'abc.onmicrosoft.com',
            clientId: '9657ca36-54f4-4064-a176-788889452',
            extraQueryParameter: 'nux=1',
            endpoints: endpoints,
            //cacheLocation: 'localStorage', // enable this for IE, as sessionStorage does not work for localhost.  
            // Also, token acquisition for the To Go API will fail in IE when running on localhost, due to IE security restrictions.
        },
        $httpProvider
        );
   `

**Comment by maliksahil** [comment]
You need to auth with a different resource id. Basically it'll work for whatever resource id you provide.
